---
# tasks file for adipriyantobpn.repo-centos
- name: include yum repository variable file
  include_vars: "repo-{{ repo_location }}.yml"

- name: configure CentOS yum repository
  yum_repository:
    name: "{{ item.key.lower() }}"
    description: "CentOS-$releasever - {{ item.key }}"
    mirrorlist: "{{ item.value.mirrorlist | default(omit) }}"
    failovermethod: priority
    baseurl: "{{ item.value.baseurl | default(omit) }}"
    gpgkey: "{{ centos_gpgkey_url }}"
    gpgcheck: yes
    enabled: "{{ item.value.enabled }}"
    file: "{{ item.value.file }}"
    state: present
  become: True
  with_dict: "{{ centos_repo }}"
