---
# tasks file for adipriyantobpn.repo-centos
- name: include yum repository variable file
  include_vars: "repo-{{ repo_location }}.yml"

- name: configure CentOS yum repository
  yum_repository:
    name: "{{ item.name.lower() }}"
    description: "CentOS-$releasever - {{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ centos_gpgkey_url }}"
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
    file: "{{ item.file }}"
    state: present
  become: True
  with_items:
    - { name: Base        ,file: "CentOS-Base"      ,enabled: "{{ centos_base_enabled }}"         ,baseurl: "{{ centos_base_baseurl }}" }
    - { name: Updates     ,file: "CentOS-Base"      ,enabled: "{{ centos_updates_enabled }}"      ,baseurl: "{{ centos_updates_baseurl }}" }
    - { name: Extras      ,file: "CentOS-Base"      ,enabled: "{{ centos_extras_enabled }}"       ,baseurl: "{{ centos_extras_baseurl }}" }
    - { name: CentosPlus  ,file: "CentOS-Base"      ,enabled: "{{ centos_centosplus_enabled }}"   ,baseurl: "{{ centos_centosplus_baseurl }}" }
    - { name: CR          ,file: "CentOS-CR"        ,enabled: "{{ centos_cr_enabled }}"           ,baseurl: "{{ centos_cr_baseurl }}" }
    - { name: Fasttrack   ,file: "CentOS-fasttrack" ,enabled: "{{ centos_fasttrack_enabled }}"    ,baseurl: "{{ centos_fasttrack_baseurl }}" }
